
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HEPDataModel
{

using System;
    using System.Collections.Generic;
    
public partial class Currency
{

    public Currency()
    {

        this.ItemPriceRegs = new HashSet<ItemPriceReg>();

    }


    public short Id { get; set; }

    public string CurrencyDesignation { get; set; }



    public virtual ICollection<ItemPriceReg> ItemPriceRegs { get; set; }

}

}
