

//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HEPDataModel
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

using System.Data.Entity.Core.Objects;
using System.Linq;


public partial class HEPedmDatabaseEntities : DbContext
{
    public HEPedmDatabaseEntities()
        : base("name=HEPedmDatabaseEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public DbSet<Brand> Brands { get; set; }

    public DbSet<Category> Categories { get; set; }

    public DbSet<Country> Countries { get; set; }

    public DbSet<Currency> Currencies { get; set; }

    public DbSet<Item> Items { get; set; }

    public DbSet<ItemPriceReg> ItemPriceRegs { get; set; }

    public DbSet<Language> Languages { get; set; }

    public DbSet<MachineType> MachineTypes { get; set; }

    public DbSet<Model> Models { get; set; }

    public DbSet<OEM> OEMs { get; set; }

    public DbSet<DescriptionText> DescriptionTexts { get; set; }

    public DbSet<Manufacturer> Manufacturers { get; set; }


    [DbFunction("HEPedmDatabaseEntities", "GetItemResult")]
    public virtual IQueryable<GetItemResult_Result> GetItemResult(Nullable<int> langId)
    {

        var langIdParameter = langId.HasValue ?
            new ObjectParameter("LangId", langId) :
            new ObjectParameter("LangId", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetItemResult_Result>("[HEPedmDatabaseEntities].[GetItemResult](@LangId)", langIdParameter);
    }


    public virtual ObjectResult<GetItemListProcedure_Result> GetItemListProcedure(Nullable<int> langId)
    {

        var langIdParameter = langId.HasValue ?
            new ObjectParameter("LangId", langId) :
            new ObjectParameter("LangId", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetItemListProcedure_Result>("GetItemListProcedure", langIdParameter);
    }


    public virtual ObjectResult<ModelListProcedureResult> GetModelListProcedure(Nullable<int> langId)
    {

        var langIdParameter = langId.HasValue ?
            new ObjectParameter("LangId", langId) :
            new ObjectParameter("LangId", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ModelListProcedureResult>("GetModelListProcedure", langIdParameter);
    }

}

}

