//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HEPDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemPriceReg
    {
        public long Id { get; set; }
        public System.DateTime Period { get; set; }
        public short CurrencyId { get; set; }
        public int ItemId { get; set; }
        public decimal Value { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual Item Item { get; set; }
    }
}
