//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HEPDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public Item()
        {
            this.ItemPriceRegs = new HashSet<ItemPriceReg>();
        }
    
        public int Id { get; set; }
        public int ModelId { get; set; }
        public int CategoryId { get; set; }
        public int DescriptionId { get; set; }
        public string CatalogNumber { get; set; }
        public int CountryId { get; set; }
        public string ImageUrl { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Country Country { get; set; }
        public virtual DescriptionText DescriptionText { get; set; }
        public virtual Model Model { get; set; }
        public virtual ICollection<ItemPriceReg> ItemPriceRegs { get; set; }
    }
}
