
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HEPDataModel
{

using System;
    using System.Collections.Generic;
    
public partial class Item
{

    public Item()
    {

        this.ItemPriceRegs = new HashSet<ItemPriceReg>();

        this.OEMList = new HashSet<OEM>();

        this.DescriptionTextList = new HashSet<DescriptionText>();

    }


    public int Id { get; set; }

    public int ModelId { get; set; }

    public int CategoryId { get; set; }

    public int CountryId { get; set; }

    public string ImageUrl { get; set; }

    public string Article { get; set; }

    public decimal CostBase { get; set; }

    public decimal CostNative { get; set; }

    public bool IsAvailable { get; set; }

    public Nullable<int> ManufacturerId { get; set; }



    public virtual Category Category { get; set; }

    public virtual Country Country { get; set; }

    public virtual Model Model { get; set; }

    public virtual ICollection<ItemPriceReg> ItemPriceRegs { get; set; }

    public virtual ICollection<OEM> OEMList { get; set; }

    public virtual ICollection<DescriptionText> DescriptionTextList { get; set; }

    public virtual Manufacturer Manufacturer { get; set; }

}

}
