//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HEPDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Language
    {
        public Language()
        {
            this.Categories = new HashSet<Category>();
            this.Countries = new HashSet<Country>();
            this.DescriptionTexts = new HashSet<DescriptionText>();
            this.MachineTypes = new HashSet<MachineType>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
    
        public virtual ICollection<Category> Categories { get; set; }
        public virtual ICollection<Country> Countries { get; set; }
        public virtual ICollection<DescriptionText> DescriptionTexts { get; set; }
        public virtual ICollection<MachineType> MachineTypes { get; set; }
    }
}
