
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HEPDataModel
{

using System;
    using System.Collections.Generic;
    
public partial class Model
{

    public Model()
    {

        this.Items = new HashSet<Item>();

    }


    public int Id { get; set; }

    public MachineTypeEnum MachineTypeId { get; set; }

    public int BrandId { get; set; }

    public string ModelName { get; set; }



    public virtual Brand Brand { get; set; }

    public virtual ICollection<Item> Items { get; set; }

}

}
