
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HEPDataModel
{

using System;
    
public partial class ModelListProcedureResult
{

    public int Id { get; set; }

    public string ModelName { get; set; }

    public string BrandName { get; set; }

    public short MachineTypeId { get; set; }

}

}
